# Generated by Django 3.2.10 on 2021-12-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.AddField(
            model_name='test',
            name='members',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='membersPerGroup',
            field=models.IntegerField(default=3),
        ),
    ]
