# Generated by Django 3.2.10 on 2021-12-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0002_auto_20211220_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Round',
        ),
    ]
