# Generated by Django 3.2.10 on 2021-12-21 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0003_rename_test_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='membersPerGroup',
        ),
        migrations.AddField(
            model_name='round',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
