# Generated by Django 3.2.10 on 2021-12-28 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shuffle', '0004_auto_20211221_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstDegree', models.CharField(max_length=100)),
                ('secondDegree', models.CharField(max_length=100)),
                ('experience', models.IntegerField(max_length=100)),
                ('recruitmentYear', models.IntegerField(max_length=100)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
