# Generated by Django 3.2.10 on 2021-12-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0006_alter_staffprofile_recruitmentyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
