# Generated by Django 3.2.10 on 2021-12-28 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0007_alter_staffprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='recruitmentYear',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
