# Generated by Django 3.2.10 on 2022-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0010_round_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
