# Generated by Django 3.2.10 on 2022-01-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0011_auto_20220106_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='experience',
        ),
    ]
