# Generated by Django 3.2.10 on 2022-01-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0012_remove_staffprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='perviousOccupation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
